### PR TITLE
Add support for macOS 13.2 and 13.3

### PR DESCRIPTION
**Pull request by joseluisq**

### CODE REVIEW

**Comment by joseluisq** [comment]
On the latest Macos 13.3.1 with Xcode 14.3, I get the following error when testing this PR. Any idea why?

```sh
$ ./tools/gen_sdk_package.sh
# found Xcode: /Applications/Xcode.app
# packaging MacOSX13.3 SDK (this may take several minutes) ...
# cp: cannot overwrite directory /tmp/sOBW08OLD38/MacOSX13.3.sdk/usr/include/c++/v1/__string with non-directory Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/__string
```

**Comment by joseluisq** [comment]
I found that when copying to the temp directory at line 187 
https://github.com/tpoechtrager/osxcross/blob/ed079949e7aee248ad7e7cb97726cd1c8556afd1/tools/gen_sdk_package.sh#L186-L188

the `__string` libc++ header is already a directory rather than a regular file and has content.

```sh
$ ll /tmp/sOBW08OLD38/MacOSX13.3.sdk/usr/include/c++/v1/__string/
# char_traits.h
# extern_template_lists.h
```

**Comment by radusalagean** [comment]
@joseluisq this helped me: https://github.com/tpoechtrager/osxcross/issues/383#issuecomment-1580487598

**Comment by joseluisq** [comment]
@radusalagean I did something similar too like removing the `__string` dir before copying but I was not sure if that workaround should be fine. That's why I asked above.
So it would be great to know the maintainer's opinion about if  https://github.com/tpoechtrager/osxcross/issues/383#issuecomment-1580487598 could be acceptable or not.

**Review by jlsantiago0 — APPROVED** [review]
I used this patch to make OSXCross using 13.3 SDK from XCode-14.3.1.

**Pull request merged**
