### PR TITLE
Fix clang build. Github website changed and broke access to tarballs.

### PR DESCRIPTION
**Pull request by cschol**
Fixes https://github.com/tpoechtrager/osxcross/issues/363.

### CODE REVIEW

**Comment by philippe44** [comment]
On my system, there is an extra set of quotes around LLVM_PKG and CLANG_PKG that breaks the download through wget. As well,  llvm does not build as some cmake items seems to be missing for 15.x

**Comment by cschol** [comment]
> On my system, there is an extra set of quotes around LLVM_PKG and CLANG_PKG that breaks the download through wget. As well, llvm does not build as some cmake items seems to be missing for 15.x

The quote issue has been fixed in the latest update to PR. The `LLVM` build failure you are reporting is a different issue. The build completes successfully for clang 12.0.1 with my fix applied.

**Review by Flow86 — APPROVED** [review]
Successfully used this patch to build clang

**Comment by akien-mga** [comment]
@tpoechtrager Any chance to see this or #336 merged? `build_clang.sh` is broken currently.

**Comment by tpoechtrager** [comment]
Merged #363. Thanks for your Pull Request though.

**Pull request closed without merging**
